/*******************************************************************************
 * Copyright (c) 2013 Loetz KG (Heidelberg), Petra Bierleutgeb and others. All rights reserved. This program and the
 * accompanying materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 ******************************************************************************/

/*
 * generated by Xtext
 */
package org.lunifera.doc.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.XtextSourceViewer;
import org.eclipse.xtext.ui.editor.formatting.IContentFormatterFactory;
import org.lunifera.doc.dsl.ui.formatting.FormatterFactory;
import org.lunifera.doc.dsl.ui.ide.editor.RichStringAwareSourceViewer;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LuniferaDocGrammarUiModule extends
		org.lunifera.doc.dsl.ui.AbstractLuniferaDocGrammarUiModule {
	public LuniferaDocGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends XtextSourceViewer.Factory> bindSourceViewerFactory() {
		return RichStringAwareSourceViewer.Factory.class;
	}
	
	@Override
	public Class<? extends IContentFormatterFactory> bindIContentFormatterFactory() {
		return FormatterFactory.class;
	}
	
}
