/*******************************************************************************
 * Copyright (c) 2013 Loetz KG (Heidelberg), Petra Bierleutgeb and others. All rights reserved. This program and the
 * accompanying materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
 ******************************************************************************/

/*
 * generated by Xtext
 */
package org.lunifera.doc.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LuniferaDocGrammarUiModule extends
		org.lunifera.doc.dsl.ui.AbstractLuniferaDocGrammarUiModule {
	public LuniferaDocGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
