/**
 * Copyright (c) 2013 Loetz KG (Heidelberg), Petra Bierleutgeb and others.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */
package org.lunifera.doc.dsl.tests.dtodoc;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.util.IAcceptor;
import org.eclipse.xtext.xbase.compiler.CompilationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.util.ReflectExtensions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.lunifera.doc.dsl.LuniferaDocGrammarInjectorProvider;
import org.lunifera.doc.dsl.tests.util.LuniferaDocTestHelper;

@RunWith(XtextRunner.class)
@InjectWith(LuniferaDocGrammarInjectorProvider.class)
@SuppressWarnings("all")
public class CompilerTest {
  @Inject
  @Extension
  private CompilationTestHelper _compilationTestHelper;
  
  @Inject
  @Extension
  private ReflectExtensions _reflectExtensions;
  
  @Test
  public void compareGeneratedJava() {
    try {
      final StringBuilder testDoc = LuniferaDocTestHelper.loadTestModel("/org/lunifera/doc/dsl/tests/testmodels/DTODocument.luniferadoc");
      final IAcceptor<CompilationTestHelper.Result> _function = new IAcceptor<CompilationTestHelper.Result>() {
        public void accept(final CompilationTestHelper.Result it) {
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("package doc.dto;");
          _builder.newLine();
          _builder.newLine();
          _builder.append("import java.util.List;");
          _builder.newLine();
          _builder.append("import org.eclipse.xtend2.lib.StringConcatenation;");
          _builder.newLine();
          _builder.append("import org.lunifera.doc.dsl.api.document.IDTODocument;");
          _builder.newLine();
          _builder.append("import org.lunifera.doc.dsl.api.document.IDTOProperty;");
          _builder.newLine();
          _builder.newLine();
          _builder.append("@SuppressWarnings(\"all\")");
          _builder.newLine();
          _builder.append("public class MyDTO implements IDTODocument {");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("@SuppressWarnings(\"all\")");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public class PropA implements IDTOProperty {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public PropA() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.name = \"propA\";");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.description = serializeDescription().toString();");
          _builder.newLine();
          _builder.append("      ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public CharSequence serializeDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("StringConcatenation _builder = new StringConcatenation();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"This is the \");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"<b>\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"description\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"</b>\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\" of property A...\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return _builder;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getName() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public void setName(final String name) {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.name = name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public void setDescription(final String description) {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.description = description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("@SuppressWarnings(\"all\")");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public class PropB implements IDTOProperty {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public PropB() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.name = \"propB\";");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.description = serializeDescription().toString();");
          _builder.newLine();
          _builder.append("      ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public CharSequence serializeDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("StringConcatenation _builder = new StringConcatenation();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"This is the description of property B.\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return _builder;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getName() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public void setName(final String name) {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.name = name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public void setDescription(final String description) {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.description = description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private String name;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private String dtoClass;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private String description;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private List<IDTOProperty> properties;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public MyDTO() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.name = \"doc.dto.MyDTO\";");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.dtoClass = \"org.lunifera.sample.MyDTO\";");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.description = serializeDescription().toString();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.properties = new java.util.ArrayList<IDTOProperty>();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.properties.add(new PropA());");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.properties.add(new PropB());");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public CharSequence serializeDescription() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("StringConcatenation _builder = new StringConcatenation();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a id=\\\">\");_builder.append(\"intro\");_builder.append(\"\\\" class=\\\"lundoc-chapter\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"Introduction\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a id=\\\">\");_builder.append(\"overview\");_builder.append(\"\\\" class=\\\"lundoc-section\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"General Overview\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a id=\\\">\");_builder.append(\"further_info\");_builder.append(\"\\\" class=\\\"lundoc-subsection\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"Further information\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<h1>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"This is MyDTO.\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</h1>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<h2>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"h2 headline\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</h2>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<h3>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"h3 headline\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</h3>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<h4>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"h4 headline\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</h4>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<h5>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"h5 headline\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</h5>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<h6>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"h6 headline\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</h6>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"This \");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<span style=\\\"text-decoration: underline;\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"is\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</span>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\" an \");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a href=\\\"\");_builder.append(\"http://www.example.org\");_builder.append(\"\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"example url\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"It can span \");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<i>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"multiple\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</i>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\" lines.\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"You \");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<span style=\\\"my-custom-css\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"can\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</span>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\" also include images: \");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<img src=\\\"\");_builder.append(\"http://www.example.org/image.png\");_builder.append(\"\\\" alt=\\\"\");_builder.append(\"example image\");_builder.append(\"\\\" width=\\\"\");_builder.append(\"150px\");_builder.append(\"\\\" height=\\\"\");_builder.append(\"50px\");_builder.append(\"\\\" />\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"Embed email addresses like \");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a href=\\\"mailto:\");_builder.append(\"somebody@example.org\");_builder.append(\"\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"this\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"Embed skype links: \");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a href=\\\"skype:\");_builder.append(\"echo123\");_builder.append(\"?call\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"call echo123\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<div class=\\\"lundoc-sourcecode\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"\\t\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"public static void main(String[] args) {\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"\\t\\t\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"System.out.println(\\\"Hello World!\\\");\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"\\t\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"}\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</div>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<video width=\\\"\");_builder.append(\"400px\");_builder.append(\"\\\" height=\\\"\");_builder.append(\"300px\");_builder.append(\"\\\" controls>\");_builder.append(\"<source src=\\\"\");_builder.append(\"myMovie.mp4\");_builder.append(\"\\\" type=\\\"\");_builder.append(\"video/mp4\");_builder.append(\"\\\" />\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"\\t\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"Your browser does not support HTML5 video.\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</video>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a href=\\\"#\");_builder.append(\"intro\");_builder.append(\"\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"Link ref to intro chapter\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a href=\\\"link/to/\");_builder.append(\"some.view.id\");_builder.append(\"\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"open view xyz\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<a href=\\\"link/to/\");_builder.append(\"some.process.id\");_builder.append(\"\\\">\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"start process xyz\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</a>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<table>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<tr>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"a\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"b\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"c\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"d\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</tr>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<tr>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"d\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"e\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"f\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</td>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</tr>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</table>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<ul>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"a\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"b\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"c\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</ul>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<ol>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"a\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"b\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"<li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"c\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</li>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"</ol>\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("{");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("boolean _lessThan = (2 < 5);");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("if (_lessThan) {");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("_builder.append(\"abc\");");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("} else {");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("boolean _equals = (2 == 5);");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("if (_equals) {");
          _builder.newLine();
          _builder.append("          ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("          ");
          _builder.append("_builder.append(\"xyz\");");
          _builder.newLine();
          _builder.append("          ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("          ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("        ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return _builder;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public String getName() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return this.name;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public String getDtoClass() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return this.dtoClass;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public String getDescription() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return serializeDescription().toString();");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public List<IDTOProperty> getProperties() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return this.properties;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("}");
          _builder.newLine();
          String _string = _builder.toString();
          String _singleGeneratedCode = it.getSingleGeneratedCode();
          Assert.assertEquals(_string, _singleGeneratedCode);
        }
      };
      this._compilationTestHelper.compile(testDoc, _function);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
