/*
* generated by Xtext
*/
package org.lunifera.doc.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.lunifera.doc.dsl.services.LuniferaDocGrammarGrammarAccess;

public class LuniferaDocGrammarParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LuniferaDocGrammarGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.lunifera.doc.dsl.parser.antlr.internal.InternalLuniferaDocGrammarParser createParser(XtextTokenStream stream) {
		return new org.lunifera.doc.dsl.parser.antlr.internal.InternalLuniferaDocGrammarParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "NamedDocument";
	}
	
	public LuniferaDocGrammarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LuniferaDocGrammarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
