/**
 * Copyright (c) 2013 Loetz KG (Heidelberg), Petra Bierleutgeb and others.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 */
package org.lunifera.doc.dsl.tests.entitydoc;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.util.IAcceptor;
import org.eclipse.xtext.xbase.compiler.CompilationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.util.ReflectExtensions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.lunifera.doc.dsl.LuniferaDocGrammarInjectorProvider;
import org.lunifera.doc.dsl.tests.util.LuniferaDocTestHelper;

@RunWith(XtextRunner.class)
@InjectWith(LuniferaDocGrammarInjectorProvider.class)
@SuppressWarnings("all")
public class CompilerTest {
  @Inject
  @Extension
  private CompilationTestHelper _compilationTestHelper;
  
  @Inject
  @Extension
  private ReflectExtensions _reflectExtensions;
  
  @Test
  public void compareGeneratedJava() {
    try {
      final StringBuilder testDoc = LuniferaDocTestHelper.loadTestModel("/org/lunifera/doc/dsl/tests/testmodels/EntityDocument.luniferadoc");
      final IAcceptor<CompilationTestHelper.Result> _function = new IAcceptor<CompilationTestHelper.Result>() {
        public void accept(final CompilationTestHelper.Result it) {
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("package doc.entity;");
          _builder.newLine();
          _builder.newLine();
          _builder.append("import java.util.List;");
          _builder.newLine();
          _builder.append("import org.eclipse.xtend2.lib.StringConcatenation;");
          _builder.newLine();
          _builder.append("import org.lunifera.doc.dsl.api.document.IEntityDocument;");
          _builder.newLine();
          _builder.append("import org.lunifera.doc.dsl.api.document.IEntityField;");
          _builder.newLine();
          _builder.newLine();
          _builder.append("@SuppressWarnings(\"all\")");
          _builder.newLine();
          _builder.append("public class MyEntityDoc implements IEntityDocument {");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("@SuppressWarnings(\"all\")");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public class FieldA implements IEntityField {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String type;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private Integer length;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private Boolean pk;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private Boolean nullable;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public FieldA() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.name = \"fieldA\";");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.type = \"int\";");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.length = 11;");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.pk = true;");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.nullable = false;");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.description = serializeDescription().toString();");
          _builder.newLine();
          _builder.append("      ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public CharSequence serializeDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("StringConcatenation _builder = new StringConcatenation();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"This is the description of fieldA. FieldA is of type int(11), a primary key and hence not nullable.\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return _builder;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getName() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getType() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.type;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public Integer getLength() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.length;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public Boolean getPk() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.pk;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public Boolean getNullable() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.nullable;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("@SuppressWarnings(\"all\")");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public class FieldB implements IEntityField {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String type;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private Integer length;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private Boolean pk;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private Boolean nullable;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("private String description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public FieldB() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.name = \"fieldB\";");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.type = \"varchar\";");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.length = 255;");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.pk = false;");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.nullable = true;");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("this.description = serializeDescription().toString();");
          _builder.newLine();
          _builder.append("      ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public CharSequence serializeDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("StringConcatenation _builder = new StringConcatenation();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"This is the \");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"<h2>\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"description\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\"</h2>\");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.append(\" of property B. This field is nullable. \");");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLineIfNotEmpty();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("_builder.newLine();");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return _builder;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getName() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.name;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getType() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.type;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public Integer getLength() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.length;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public Boolean getPk() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.pk;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public Boolean getNullable() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.nullable;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("    ");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("public String getDescription() {");
          _builder.newLine();
          _builder.append("      ");
          _builder.append("return this.description;");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private String name;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private String entityClass;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private String description;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("private List<IEntityField> fields;");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public MyEntityDoc() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.name = \"doc.entity.MyEntityDoc\";");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.entityClass = \"org.lunifera.sample.MyEntity\";");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.description = serializeDescription().toString();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.fields = new java.util.ArrayList<IEntityField>();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.fields.add(new FieldA());");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("this.fields.add(new FieldB());");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public CharSequence serializeDescription() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("StringConcatenation _builder = new StringConcatenation();");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("_builder.append(\"This is MyEntity\");");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return _builder;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public String getName() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return this.name;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public String getEntityClass() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return this.entityClass;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public String getDescription() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return this.description;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("  ");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("public List<IEntityField> getFields() {");
          _builder.newLine();
          _builder.append("    ");
          _builder.append("return this.fields;");
          _builder.newLine();
          _builder.append("  ");
          _builder.append("}");
          _builder.newLine();
          _builder.append("}");
          _builder.newLine();
          String _string = _builder.toString();
          String _singleGeneratedCode = it.getSingleGeneratedCode();
          Assert.assertEquals(_string, _singleGeneratedCode);
        }
      };
      this._compilationTestHelper.compile(testDoc, _function);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
