/**
 *
 * $Id$
 */
package org.lunifera.doc.dsl.luniferadoc.richstring.validation;


/**
 * A sample validator interface for {@link org.lunifera.doc.dsl.luniferadoc.richstring.RichStringBox}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RichStringBoxValidator {
	boolean validate();

	boolean validateError(boolean value);
	boolean validateWarning(boolean value);
	boolean validateInfo(boolean value);
	boolean validateAbstracts(boolean value);
	boolean validateChecklist(boolean value);
	boolean validateBio(boolean value);
	boolean validateSidenote(boolean value);
	boolean validateTitle(String value);
}
