/*
 * generated by Xtext
 */
package org.lunifera.doc.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.lunifera.doc.dsl.ui.internal.LuniferaDocGrammarActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LuniferaDocGrammarExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LuniferaDocGrammarActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LuniferaDocGrammarActivator.getInstance().getInjector(LuniferaDocGrammarActivator.ORG_LUNIFERA_DOC_DSL_LUNIFERADOCGRAMMAR);
	}
	
}
