<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="doccompiler" nsURI="http://www.lunifera.org/documentation/compiler/v1"
    nsPrefix="ldoccompiler">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="fileExtensions" value="doccompiler"/>
    <details key="modelName" value="LuniferaDocCompiler"/>
    <details key="prefix" value="LDocCompiler"/>
    <details key="operationReflection" value="false"/>
    <details key="basePackage" value="org.lunifera.doc.dsl.luniferadoc"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="rootPackage" value="ldoccompiler"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//ProcessedRichString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//DocumentEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" eType="ecore:EClass luniferadoc.ecore#//LDocNamedDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//DocumentStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessedRichString">
    <eStructuralFeatures xsi:type="ecore:EReference" name="richString" eType="ecore:EClass richstring.ecore#//RichString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//Line" containment="true" resolveProxies="false" eOpposite="#//Line/richString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//LinePart" containment="true" resolveProxies="false" eOpposite="#//LinePart/line"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="richString" eType="#//ProcessedRichString"
        eOpposite="#//ProcessedRichString/lines"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="#//Line" eOpposite="#//Line/parts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass richstring.ecore#//RichStringLiteral"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Offset" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineBreak" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoopStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loop" eType="ecore:EClass richstring.ecore#//RichStringForLoop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ForLoopEnd"
        eOpposite="#//ForLoopEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoopEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ForLoopStart"
        eOpposite="#//ForLoopStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrintedExpression" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfConditionStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="richStringIf" eType="ecore:EClass richstring.ecore#//RichStringIf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseStart" eType="#//ElseStart"
        eOpposite="#//ElseStart/ifConditionStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfConditions" upperBound="-1"
        eType="#//ElseIfCondition" eOpposite="#//ElseIfCondition/ifConditionStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endIf" eType="#//EndIf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseIfCondition" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="richStringElseIf" eType="ecore:EClass richstring.ecore#//RichStringElseIf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionStart" eType="#//IfConditionStart"
        eOpposite="#//IfConditionStart/elseIfConditions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionStart" eType="#//IfConditionStart"
        eOpposite="#//IfConditionStart/elseStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndIf" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionStart" eType="#//IfConditionStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Markup" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="markup" eType="ecore:EClass richstring.ecore#//RichStringMarkup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H1Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringH1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H1End"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H1End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H1Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H2Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringH2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H2End"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H2End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H2Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H3Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringH3"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H3End"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H3End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H3Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H4Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringH4"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H4End"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H4End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H4Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H5Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringH5"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H5End"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H5End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H5Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H6Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringH6"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H6End"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H6End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H6Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringExample"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ExampleEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ExampleStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URLStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringURL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//URLEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URLEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//URLStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//RefEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//RefStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoldStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringBold"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//BoldEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoldEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//BoldStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnderlineStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringUnderline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//UnderlineEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnderlineEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//UnderlineStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItalicStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringItalic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ItalicEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItalicEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ItalicStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpanStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringSpan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SpanEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpanEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SpanStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImgStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringImg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ImgEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImgEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ImgStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MailtoStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringMailto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//MailtoEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MailtoEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//MailtoStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkypeStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringSkype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SkypeEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkypeEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SkypeStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovieStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringMovie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//MovieEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovieEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//MovieStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringCode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//CodeEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//CodeStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringTable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TableEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TableStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringTableRow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TableRowEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TableRowStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringTableCell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TableCellEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TableCellStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ListEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ListStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedListStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringOrderedList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//OrderedListEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedListEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//OrderedListStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListElementStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringListElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ListElementEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListElementEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ListElementStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChapterStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringChapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ChapterEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChapterEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ChapterStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SectionEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SectionStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSectionStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringSubsection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SubSectionEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSectionEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SubSectionStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenViewStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringOpenView"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//OpenViewEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenViewEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//OpenViewStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartProcessStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringStartProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//StartProcessEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartProcessEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//StartProcessStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringEntityRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//EntityRefEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//EntityRefStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTORefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringDTORef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//DTORefEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTORefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//DTORefStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringProcessRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ProcessRefEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ProcessRefStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringTaskRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TaskRefEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TaskRefStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringViewRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ViewRefEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ViewRefStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.ecore#//RichStringUIRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//UIRefEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//UIRefStart"/>
  </eClassifiers>
</ecore:EPackage>
