<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="doccompiler" nsURI="http://www.lunifera.org/doccompiler" nsPrefix="doccompiler">
  <eClassifiers xsi:type="ecore:EClass" name="DocumentStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//ProcessedRichString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//DocumentEnd"
        eOpposite="#//DocumentEnd/start"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" eType="ecore:EClass LuniferaDocGrammar.ecore#//NamedDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//DocumentStart"
        eOpposite="#//DocumentStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessedRichString">
    <eStructuralFeatures xsi:type="ecore:EReference" name="richString" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//Line" containment="true" eOpposite="#//Line/richString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//LinePart" containment="true" eOpposite="#//LinePart/line"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="richString" eType="#//ProcessedRichString"
        eOpposite="#//ProcessedRichString/lines"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="#//Line" eOpposite="#//Line/parts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringLiteral"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineBreak" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoopStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loop" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringForLoop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ForLoopEnd"
        eOpposite="#//ForLoopEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForLoopEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ForLoopStart"
        eOpposite="#//ForLoopStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrintedExpression" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfConditionStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="richStringIf" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringIf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseStart" eType="#//ElseStart"
        eOpposite="#//ElseStart/ifConditionStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfConditions" upperBound="-1"
        eType="#//ElseIfCondition" eOpposite="#//ElseIfCondition/ifConditionStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endIf" eType="#//EndIf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseIfCondition" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="richStringElseIf" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringElseIf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionStart" eType="#//IfConditionStart"
        eOpposite="#//IfConditionStart/elseIfConditions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionStart" eType="#//IfConditionStart"
        eOpposite="#//IfConditionStart/elseStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndIf" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConditionStart" eType="#//IfConditionStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Markup" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="markup" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringMarkup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H1Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringH1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H1End" eOpposite="#//H1End/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H1End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H1Start"
        eOpposite="#//H1Start/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H2Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringH2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H2End" eOpposite="#//H2End/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H2End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H2Start"
        eOpposite="#//H2Start/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H3Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringH3"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H3End" eOpposite="#//H3End/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H3End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H3Start"
        eOpposite="#//H3Start/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H4Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringH4"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H4End" eOpposite="#//H4End/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H4End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H4Start"
        eOpposite="#//H4Start/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H5Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringH5"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H5End" eOpposite="#//H5End/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H5End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H5Start"
        eOpposite="#//H5Start/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H6Start" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringH6"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//H6End" eOpposite="#//H6End/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="H6End" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//H6Start"
        eOpposite="#//H6Start/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringExample"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ExampleEnd"
        eOpposite="#//ExampleEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ExampleStart"
        eOpposite="#//ExampleStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URLStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringURL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//URLEnd"
        eOpposite="#//URLEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URLEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//URLStart"
        eOpposite="#//URLStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//RefEnd"
        eOpposite="#//RefEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//RefStart"
        eOpposite="#//RefStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoldStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringBold"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//BoldEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoldEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//BoldStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnderlineStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringUnderline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//UnderlineEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnderlineEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//UnderlineStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItalicStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringItalic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ItalicEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItalicEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ItalicStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpanStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringSpan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SpanEnd"
        eOpposite="#//SpanEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpanEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SpanStart"
        eOpposite="#//SpanStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImgStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringImg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ImgEnd"
        eOpposite="#//ImgEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImgEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ImgStart"
        eOpposite="#//ImgStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MailtoStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringMailto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//MailtoEnd"
        eOpposite="#//MailtoEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MailtoEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//MailtoStart"
        eOpposite="#//MailtoStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkypeStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringSkype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SkypeEnd"
        eOpposite="#//SkypeEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkypeEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SkypeStart"
        eOpposite="#//SkypeStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovieStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringMovie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//MovieEnd"
        eOpposite="#//MovieEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovieEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//MovieStart"
        eOpposite="#//MovieStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringCode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//CodeEnd"
        eOpposite="#//CodeEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//CodeStart"
        eOpposite="#//CodeStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringTable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringTableRow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TableEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TableStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringTableRow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringTableData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TableRowEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TableRowStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableDataStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringTableData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TableDataEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableDataEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TableDataStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ListElementStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ListEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ListStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedListStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringOrderedList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ListElementStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//OrderedListEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedListEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//OrderedListStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListElementStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringListElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ListElementEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListElementEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ListElementStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChapterStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringChapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ChapterEnd"
        eOpposite="#//ChapterEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChapterEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ChapterStart"
        eOpposite="#//ChapterStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SectionEnd"
        eOpposite="#//SectionEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SectionStart"
        eOpposite="#//SectionStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubsectionStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringSubsection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//SubsectionEnd"
        eOpposite="#//SubsectionEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubsectionEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//SubsectionStart"
        eOpposite="#//SubsectionStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenViewStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringOpenView"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//OpenViewEnd"
        eOpposite="#//OpenViewEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenViewEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//OpenViewStart"
        eOpposite="#//OpenViewStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartProcessStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringStartProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//StartProcessEnd"
        eOpposite="#//StartProcessEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartProcessEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//StartProcessStart"
        eOpposite="#//StartProcessStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringEntityRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//EntityRefEnd"
        eOpposite="#//EntityRefEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//EntityRefStart"
        eOpposite="#//EntityRefStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTORefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringDTORef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//DTORefEnd"
        eOpposite="#//DTORefEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DTORefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//DTORefStart"
        eOpposite="#//DTORefStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringProcessRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ProcessRefEnd"
        eOpposite="#//ProcessRefEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ProcessRefStart"
        eOpposite="#//ProcessRefStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringTaskRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//TaskRefEnd"
        eOpposite="#//TaskRefEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//TaskRefStart"
        eOpposite="#//TaskRefStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringViewRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//ViewRefEnd"
        eOpposite="#//ViewRefEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//ViewRefStart"
        eOpposite="#//ViewRefStart/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIRefStart" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass LuniferaDocGrammar.ecore#//richstring/RichStringUIRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//UIRefEnd"
        eOpposite="#//UIRefEnd/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIRefEnd" eSuperTypes="#//LinePart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//UIRefStart"
        eOpposite="#//UIRefStart/end"/>
  </eClassifiers>
</ecore:EPackage>
