<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="luniferadoc" nsURI="http://www.lunifera.org/luniferadoc" nsPrefix="luniferadoc">
  <eClassifiers xsi:type="ecore:EEnum" name="DocType">
    <eLiterals name="ENTITY"/>
    <eLiterals name="DTO" value="1"/>
    <eLiterals name="BPM_PROCESS" value="2" literal=""/>
    <eLiterals name="BPM_TASK" value="3"/>
    <eLiterals name="VAACLIPSE_VIEW" value="4"/>
    <eLiterals name="UI" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedDocument" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentInclude">
    <eStructuralFeatures xsi:type="ecore:EReference" name="include" eType="#//document/LuniferaDocDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="document" nsURI="http://www.lunifera.org/luniferadoc/document"
      nsPrefix="document">
    <eClassifiers xsi:type="ecore:EClass" name="LuniferaDocDocument" abstract="true"
        interface="true" eSuperTypes="#//NamedDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="EntityDocument" eSuperTypes="#//document/LuniferaDocDocument">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//document/EntityDescription"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" eType="#//document/EntityFields"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntityDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//richstring/RichString"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntityFields">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
          eType="#//document/EntityField" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntityField">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//richstring/RichString"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DTODocument" eSuperTypes="#//document/LuniferaDocDocument">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtoClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//document/DTODescription"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="details" eType="#//document/DTODetails"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DTODescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//richstring/RichString"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DTODetails">
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//document/DTOProperty" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DTOProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//richstring/RichString"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BPMProcessDocument" eSuperTypes="#//document/LuniferaDocDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="BPMTaskDocument" eSuperTypes="#//document/LuniferaDocDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="VaaclipseViewDocument" eSuperTypes="#//document/LuniferaDocDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="UIDocument" eSuperTypes="#//document/LuniferaDocDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="GeneralDocument" eSuperTypes="#//layout/LuniferaDocLayout">
      <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
          eType="#//DocumentInclude" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="layout" nsURI="http://www.lunifera.org/luniferadoc/layout" nsPrefix="layout">
    <eClassifiers xsi:type="ecore:EClass" name="LuniferaDocLayout" abstract="true"
        interface="true" eSuperTypes="#//NamedDocument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//richstring/RichString"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.eclipse.xtext.xbase/model/Xtype.ecore#//XImportDeclaration"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntityLayout" eSuperTypes="#//layout/LuniferaDocLayout"/>
    <eClassifiers xsi:type="ecore:EClass" name="DTOLayout" eSuperTypes="#//layout/LuniferaDocLayout"/>
    <eClassifiers xsi:type="ecore:EClass" name="BPMProcessLayout" eSuperTypes="#//layout/LuniferaDocLayout"/>
    <eClassifiers xsi:type="ecore:EClass" name="BPMTaskLayout" eSuperTypes="#//layout/LuniferaDocLayout"/>
    <eClassifiers xsi:type="ecore:EClass" name="VaaclipseViewLayout" eSuperTypes="#//layout/LuniferaDocLayout"/>
    <eClassifiers xsi:type="ecore:EClass" name="UILayout" eSuperTypes="#//layout/LuniferaDocLayout"/>
  </eSubpackages>
  <eSubpackages name="richstring" nsURI="http://www.lunifera.org/luniferadoc/richstring"
      nsPrefix="richstring">
    <eClassifiers xsi:type="ecore:EClass" name="RichStringElseIf">
      <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichString" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringLiteral" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XStringLiteral"/>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringForLoop" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XForLoopExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="before" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="separator" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="after" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringIf" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfs" upperBound="-1"
          eType="#//richstring/RichStringElseIf" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringMarkup" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringExample" eSuperTypes="#//richstring/RichStringMarkup"/>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringH1" eSuperTypes="#//richstring/RichStringMarkup"/>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringH2" eSuperTypes="#//richstring/RichStringMarkup"/>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringURL" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="markup" nsURI="http://www.lunifera.org/luniferadoc/markup" nsPrefix="markup">
    <eClassifiers xsi:type="ecore:EClass" name="TagURL">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//richstring/RichString"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
