<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="luniferadoc" nsURI="http://www.lunifera.org/documentation/v1"
    nsPrefix="luniferadoc">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="fileExtensions" value="docu"/>
    <details key="modelName" value="LuniferaDoc"/>
    <details key="prefix" value="LDoc"/>
    <details key="operationReflection" value="false"/>
    <details key="basePackage" value="org.lunifera.doc.dsl"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="rootPackage" value="luniferadoc"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="LDocNamedDocument" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocInclude">
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" eType="#//LDocDocument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" unique="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provided" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedType" unique="false"
        eType="#//LDocType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedJVMType" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocDocument" abstract="true" interface="true"
      eSuperTypes="#//LDocNamedDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass richstring.xcore#/EPackage/RichString"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocEntityDocument" eSuperTypes="#//LDocDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//LDocEntityField" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocEntityField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass richstring.xcore#/EPackage/RichString"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocDtoDocument" eSuperTypes="#//LDocDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//LDocDtoProperty" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocDtoProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass richstring.xcore#/EPackage/RichString"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocBPMProcessDocument" eSuperTypes="#//LDocDocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="process" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocHumanTaskDocument" eSuperTypes="#//LDocDocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="task" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocViewDocument" eSuperTypes="#//LDocDocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="view" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocUIDocument" eSuperTypes="#//LDocDocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ui" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LDocLayouter" eSuperTypes="#//LDocNamedDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass richstring.xcore#/EPackage/RichString"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xtype.ecore#//XImportDeclaration"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//LDocInclude" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LDocType">
    <eLiterals name="DTO"/>
    <eLiterals name="ENTITY" value="1"/>
  </eClassifiers>
</ecore:EPackage>
