<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="richstring" nsURI="http://www.lunifera.org/documentation/richstring/v1"
    nsPrefix="richstring">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="fileExtensions" value="richstring"/>
    <details key="modelName" value="LDocRichstring"/>
    <details key="prefix" value="LDocRichstring"/>
    <details key="operationReflection" value="false"/>
    <details key="basePackage" value="org.lunifera.doc.dsl.luniferadoc"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="rootPackage" value="richstring"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RichString" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringElseIf" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringLiteral" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XStringLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringForLoop" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XForLoopExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="before" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="separator" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="after" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringIf" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfs" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringMarkup" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleClass" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringExample" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringH1" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringH2" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringH3" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringH4" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringH5" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringH6" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringChapter" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringSection" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringSubsection" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringURL" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" unique="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringRef" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refId" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringBold" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringUnderline" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringItalic" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringImg" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alt" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" unique="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringMailto" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringSkype" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" unique="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringMovie" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" unique="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringCode" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lang" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringTable" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringTableRow" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringTableCell" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringOpenView" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewId" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringStartProcess" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processId" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringEntityRef" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityDoc" eType="ecore:EClass luniferadoc.xcore#/EPackage/LDocEntityDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringDTORef" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtoDoc" eType="ecore:EClass luniferadoc.xcore#/EPackage/LDocDtoDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringTaskRef" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskDoc" eType="ecore:EClass luniferadoc.xcore#/EPackage/LDocHumanTaskDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringProcessRef" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bpmDoc" eType="ecore:EClass luniferadoc.xcore#/EPackage/LDocBPMProcessDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringViewRef" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewDoc" eType="ecore:EClass luniferadoc.xcore#/EPackage/LDocViewDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringUIRef" eSuperTypes="#//RichStringMarkup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiDoc" eType="ecore:EClass luniferadoc.xcore#/EPackage/LDocUIDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringList" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringOrderedList" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringListElement" eSuperTypes="#//RichStringMarkup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RichStringSpan" eSuperTypes="#//RichStringMarkup"/>
</ecore:EPackage>
