/**
 *
 * $Id$
 */
package org.lunifera.doc.dsl.doccompiler.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.doc.dsl.doccompiler.ElseIfCondition;
import org.lunifera.doc.dsl.doccompiler.ElseStart;
import org.lunifera.doc.dsl.doccompiler.EndIf;

import org.lunifera.doc.dsl.luniferadoc.richstring.RichStringIf;

/**
 * A sample validator interface for {@link org.lunifera.doc.dsl.doccompiler.IfConditionStart}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfConditionStartValidator {
	boolean validate();

	boolean validateRichStringIf(RichStringIf value);
	boolean validateElseStart(ElseStart value);
	boolean validateElseIfConditions(EList<ElseIfCondition> value);
	boolean validateEndIf(EndIf value);
}
