/**
 *
 * $Id$
 */
package org.lunifera.doc.dsl.doccompiler.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.doc.dsl.doccompiler.ListElementStart;
import org.lunifera.doc.dsl.doccompiler.ListEnd;

import org.lunifera.doc.dsl.luniferadoc.richstring.RichStringList;

/**
 * A sample validator interface for {@link org.lunifera.doc.dsl.doccompiler.ListStart}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ListStartValidator {
	boolean validate();

	boolean validateContent(RichStringList value);
	boolean validateElements(EList<ListElementStart> value);
	boolean validateEnd(ListEnd value);
}
