/**
 *
 * $Id$
 */
package org.lunifera.doc.dsl.doccompiler.validation;

import org.lunifera.doc.dsl.doccompiler.MovieEnd;

import org.lunifera.doc.dsl.luniferadoc.richstring.RichStringMovie;

/**
 * A sample validator interface for {@link org.lunifera.doc.dsl.doccompiler.MovieStart}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MovieStartValidator {
	boolean validate();

	boolean validateContent(RichStringMovie value);
	boolean validateEnd(MovieEnd value);
}
