/**
 *
 * $Id$
 */
package org.lunifera.doc.dsl.doccompiler.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.doc.dsl.doccompiler.TableEnd;

import org.lunifera.doc.dsl.luniferadoc.richstring.RichStringTable;
import org.lunifera.doc.dsl.luniferadoc.richstring.RichStringTableRow;

/**
 * A sample validator interface for {@link org.lunifera.doc.dsl.doccompiler.TableStart}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableStartValidator {
	boolean validate();

	boolean validateContent(RichStringTable value);
	boolean validateRows(EList<RichStringTableRow> value);
	boolean validateEnd(TableEnd value);
}
