/*
* generated by Xtext
*/
package org.lunifera.doc.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LuniferaDocGrammarStandaloneSetup extends LuniferaDocGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new LuniferaDocGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

