/*******************************************************************************
 * Copyright (c) 2013 Lunifera GmbH, Petra Bierleutgeb and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/

/*
* generated by Xtext
*/
package org.lunifera.doc.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LuniferaDocGrammarStandaloneSetup extends LuniferaDocGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new LuniferaDocGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

