/**
 *
 * $Id$
 */
package org.lunifera.doc.dsl.luniferadoc.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.xtype.XImportDeclaration;

import org.lunifera.doc.dsl.luniferadoc.LDocInclude;

import org.lunifera.doc.dsl.luniferadoc.richstring.RichString;

/**
 * A sample validator interface for {@link org.lunifera.doc.dsl.luniferadoc.LDocLayouter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LDocLayouterValidator {
	boolean validate();

	boolean validateContent(RichString value);
	boolean validateImports(EList<XImportDeclaration> value);
	boolean validateIncludes(EList<LDocInclude> value);

	boolean validateProvided(EList<LDocInclude> value);
}
