/**
 *
 * $Id$
 */
package org.lunifera.doc.dsl.luniferadoc.validation;

import org.eclipse.emf.common.util.EList;

import org.lunifera.doc.dsl.luniferadoc.LDocEntityField;

import org.lunifera.dsl.semantic.common.types.LType;

/**
 * A sample validator interface for {@link org.lunifera.doc.dsl.luniferadoc.LDocEntityDocument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LDocEntityDocumentValidator {
	boolean validate();

	boolean validateFields(EList<LDocEntityField> value);
	boolean validateModel(LType value);
}
